### ISSUE TITLE
edit boxes do not echo back to the screen reader in OS X

### ISSUE THREAD

**Issue by n7zzt** [h3poteto/whalebird-desktop#660]
Apparently, the edit boxes (often the toot or reply edit boxes) do not echo back to the screen reader (OS X Voiceover), thus not leaving me with a way to insure that I am actually typing inside the edit box. I do have a work around, but it's very inconvenient and not entirely usable if I need to edit the contents therein. not sure if there is any universal accessibility code in the IDE, but if there is, I highly recommend it's use. I happen to be blind here, so accessibility is of high priority for me.

thanks.

**Comment by h3poteto** [comment]
I understand it, but now I can not find how to enable echo back. 
Even slack does not realize it.

I will search it a little more.

**Comment by amyspark** [comment]
Tested with VoiceOver in MacOS, I believe this was fixed in #746.

**Comment by n7zzt** [comment]
Ok, I recently updated the client, and it still doesn’t echo back when I type in the edit box for a new toot. Now, was that problem fixed under High Sierra or Mohave? Btw, the most recent update was 5 days ago for me. I may have to create a screen capture video showing the issue and then link it here from my dropbox.
